//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYTask2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        public int Id { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
    
        public virtual Sheet Sheet { get; set; }
    }
}
