//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYTask2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Circulation> Circulations { get; set; }
        public virtual DbSet<ClosingBalance> ClosingBalancies { get; set; }
        public virtual DbSet<OpeningBalance> OpeningBalancies { get; set; }
        public virtual DbSet<Sheet> Sheets { get; set; }
        public virtual DbSet<DataFile> DataFiles { get; set; }
    }
}
