//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYTask2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet
    {
        public int Id { get; set; }
        public string Class { get; set; }
        public int FileId { get; set; }
    
        public virtual Circulation Circulation { get; set; }
        public virtual ClosingBalance ClosingBalance { get; set; }
        public virtual OpeningBalance OpeningBalance { get; set; }
        public virtual DataFile DataFile { get; set; }
    }
}
